# Generated by Django 5.1.3 on 2024-12-02 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0006_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remainder_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
