# Generated by Django 5.1.3 on 2024-12-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0007_todo_remainder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='remainder_date',
        ),
    ]
