# Generated by Django 5.1.3 on 2024-12-02 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0008_remove_todo_remainder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remainder_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
